server:
  port: ${PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:personal_attendance}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:5173,https://attendance.ducit.io.vn}
